name: C++ Build and Run with CMake

on: push

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install build tools
      run: |
        choco install make  # מתקין כלים נדרשים, כמו make אם אתה בונה עם makefile

    - name: Compile all source files
      run: g++ -o main main.cpp TicTacToe.cpp  # כוללים גם את TicTacToe.cpp

    - name: Run program
      run: ./main  # הרצת התוכנית
