name: C++ Tic Tac Toe Build and Run

on: [push, pull_request]  # ירוץ בכל Push או Pull Request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install g++
        run: sudo apt-get install g++

      - name: Compile the code
        run: |
          g++ -std=c++17 -o TicTacToe main.cpp Board.cpp TicTacToe.cpp
          echo "Compilation succeeded!"

      - name: Run the game
        run: ./TicTacToe
