name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2


    - name: Set up CMake
      uses: crazy2be/cmake@v1.1.0

  
    - name: Build with CMake
      run: |
        mkdir build
        cd build
        cmake ..
        make

   
    - name: Run the game
      run: |
        cd build
        ./TicTacToe.exe
