name: C++ Build and Run with CMake

on: push

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: triadegonzales/setup-cmake@v1  

    - name: Install build tools
      run: |
        choco install make

    - name: Create build directory
      run: |
        mkdir build && cd build

    - name: Run CMake to configure the project
      run: |
        cmake ..  

    - name: Build the project
      run: |
        cmake --build .  

    - name: Run the program
      run: |
        ./cmake-build-debug/TicTacToe.exe  
