name: C++ CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # שינוי מ-ubuntu-latest ל-windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        choco install cmake
        choco install visualstudio2019buildtools
        
    - name: Configure CMake
      run: cmake -B build -S .
    
    - name: Run the program
      run: |
        .\x64\Release\tictactoe.exe

