name: C++ Build and Run with CMake

on: push

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install C++ compiler
      run: sudo apt-get update && sudo apt-get install -y g++
    
    - name: Install build tools
      run: |
        choco install make

    - name: Compile main.cpp
      run: g++ -o main main.cpp

    - name: Run program
      run: ./main  

   
