name: C++ CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # השתמש ב-Windows
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        choco install cmake
        choco install visualstudio2019buildtools
        
    - name: Configure CMake
      run: cmake -B build -S .
    
    - name: Build
      run: cmake --build build
    
    - name: Run executable
      run: |
        cmd /c ./build/TicTacToe.exe  # הפעל את קובץ ה-EXE ב-Windows
